bot:
  token: "your_bot_token_here"
collectors:
  reddit:
    enabled: true
    client_id: "EEPTh1MyXuxOmk07r0epmg"
    client_secret: "e3ifiagezkIYwnJ1wGw6E3Iyp9xT1A"
    user_agent: "CryptoNewsBot/1.0"
    subreddits:
      - "CryptoCurrency"
      - "Bitcoin"
      - "Ethereum"
      - "CryptoMarkets"
      - "CryptoNews"
      - "CryptoGem"
      - "altcoin"
      - "BTC"
      - "CryptoCurrencies"
      - "Blockchain"
      - "dogecoin"
      - "litecoin"
      - "ripple"
      - "monero"
      - "dashpay"
      - "cardano"
      - "solana"
      - "polkadot"
      - "chainlink"
      - "stellar"
      - "tezos"
      - "vechain"
      - "tronix"
      - "binancecoin"
      - "shib"
      - "avalancheavax"
      - "nearprotocol"
      - "fantomfoundation"
      - "algorand"
    keywords:
      - "bitcoin"
      - "btc"
      - "ethereum"
      - "eth"
      - "ripple"
      - "xrp"
      - "litecoin"
      - "ltc"
      - "monero"
      - "xmr"
      - "dash"
      - "cardano"
      - "ada"
      - "solana"
      - "sol"
      - "polkadot"
      - "dot"
      - "chainlink"
      - "link"
      - "stellar"
      - "xlm"
      - "tezos"
      - "xtz"
      - "vechain"
      - "vet"
      - "tron"
      - "trx"
      - "binance"
      - "bnb"
      - "shiba"
      - "shib"
      - "avalanche"
      - "avax"
      - "near"
      - "fantom"
      - "ftm"
      - "algorand"
      - "algo"
      - "crypto"
      - "price"
  block_collector:
    enabled: true
    url: "https://www.theblock.co/latest-crypto-news"
    interval: 10800  # 3 часа в секундах
database:
  host: "localhost"
  port: 5432
  name: "crypto_db"
  user: "crypto_usr"
  password: "qwerty123"
  admin_user: "postgres"
  admin_password: "admin_password"
telegram_bot:
  token: "7785241809:AAE5moOEJebySWLjf9OrW94RoPkzNY3JWnA"
processor:
  crypto_keywords:
    - "Bitcoin"
    - "BTC"
    - "Ethereum"
    - "ETH"
    - "Ripple"
    - "XRP"
    - "Litecoin"
    - "LTC"
    - "Monero"
    - "XMR"
    - "Dash"
    - "Cardano"
    - "ADA"
    - "Solana"
    - "SOL"
    - "Polkadot"
    - "DOT"
    - "Chainlink"
    - "LINK"
    - "Stellar"
    - "XLM"
    - "Tezos"
    - "XTZ"
    - "VeChain"
    - "VET"
    - "TRON"
    - "TRX"
    - "Binance"
    - "BNB"
    - "Shiba"
    - "SHIB"
    - "Avalanche"
    - "AVAX"
    - "NEAR"
    - "Fantom"
    - "FTM"
    - "Algorand"
    - "ALGO"
  sentiment_threshold: 0.1
price_collector:
  coingecko_api: "https://api.coingecko.com/api/v3"  # Базовый URL API CoinGecko
  api_key: "CG-veh6k91StnA4yR7snF7mzFDy"
source_reliability:
  reddit: 3
  the_block: 10
